version: "3"
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "${APP_HTTP_PORT}:80"
    depends_on:
      - php
      - phpmyadmin
    volumes:
      - ./webroot:/var/www/html:cached
      - ./docker/build/nginx/conf.d/server.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./docker/build/php
    restart: always
    user: "${UID}:${GID}"
    environment:
      - IS_DOCKER=true
      - COMPOSER_HOME=/var/www/html/docker/data/php/composer
    volumes:
      - ./:/var/www/html:cached
      - ./docker/build/php/php.ini:/usr/local/etc/php/php.ini:cached
      - ./docker/build/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:cached
      - /var/www/html/.git
    depends_on:
      - db
      - smtp
  db:
    image: mariadb:10.3
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      #- MYSQL_ROOT_PASSWORD=
    volumes:
      - ./docker/build/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/build/db/conf.d:/etc/mysql/conf.d
      - ./docker/data/db:/var/lib/mysql:cached
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=
    depends_on:
      - db
  smtp:
    build: ./docker/build/smtp
    restart: always
